config/routes.rb
Rails.application.routes.draw do

  root 'urls#index'

  post 'urls/create' => 'urls#create'

  get 'urls/show/:id' => 'urls#show', as: 'url_show'

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def create
    @url = Url.new(user_params)
    @url.save
    redirect_to root_path(id: @url)
  end

  def index
  end

  def show
    @url = Url.find(params[:id])
    redirect_to @url.name
  end

  private

  def user_params
    params.permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/index.html.erb
<center><h1>Url Shortener</h1></center>
<center>
<%= form_tag urls_create_path do %>
  <%= text_field_tag :name, "https://www." %>
  <%= submit_tag "shorten" %>
<% end %>
</center>

<center>
<% if params[:id] %>
  <% @url = Url.find(params[:id]) %>
  <p>url = <%= @url.name %></p>
  <p>new shortened url = <%= link_to url_show_url(@url), url_show_url(@url) %></p>
<% end %>
</center>